title: My TU Brain
description: A place for my notes and thoughts.
author: Vinh Truong
email: vinhtr.ct@gmail.com
url: "https://thvinhtruong.github.io"
repository: thvinhtruong/thvinhtruong.github.io

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

date_format: "%b %-d, %Y"

header_pages:
  - about.md
  - tags.html
  - categories.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
